---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible & ansible-lint
  - pip install ansible
  - pip install ansible-lint

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - ansible-playbook deploy.yml -i inventories/local.ini --syntax-check
  - ansible-lint deploy.yml
